services:
  app:
    image: gyus3/dietiestatesbackend-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    secrets:
      - DB_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

secrets:
  DB_PASSWORD:
    file: ./secrets/postgres-passwd.txt
  AWS_ACCESS_KEY_ID:
    file: ./secrets/aws-access-key-id.txt
  AWS_SECRET_ACCESS_KEY:
    file: ./secrets/aws-secret-access-key.txt