spring:
  application:
    name: DietiEstatesBackend
  config:
    import: "optional:configtree:/run/secrets/"

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dietiestatesdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        spatial.connection_finder: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_tKWUxvA4t/.well-known/jwks.json
          issuer-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_tKWUxvA4t

server:
  port: 8081
  servlet:
    context-path: /api

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
