
    create table if not exists addresses (
        id bigint generated by default as identity,
        city varchar(255) not null,
        postal_code varchar(255) not null,
        province varchar(255) not null,
        street varchar(255) not null,
        location geometry(Point, 4326) not null,
        primary key (id)
    );

    create table if not exists business_users (
        agency_id bigint not null,
        user_id bigint not null,
        primary key (user_id)
    );

    create table if not exists dietiestates_roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table if not exists insertion_tags (
        tags bigint not null,
        tag varchar(255)
    );

    create table if not exists insertions (
        address_id bigint not null,
        agency_id bigint not null,
        id bigint generated by default as identity,
        uploader_id bigint not null,
        description TEXT,
        primary key (id)
    );

    create table if not exists insertions_for_rent (
        rent float(53),
        id bigint not null,
        primary key (id)
    );

    create table if not exists insertions_for_sale (
        price float(53),
        id bigint not null,
        primary key (id)
    );

    create table if not exists real_estate_agencies (
        id bigint generated by default as identity,
        iban varchar(255) not null unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table if not exists real_estate_agents (
        user_id bigint not null,
        primary key (user_id)
    );

    create table if not exists real_estate_managers (
        user_id bigint not null,
        primary key (user_id)
    );

    create table if not exists user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table if not exists users (
        id bigint generated by default as identity,
        cognito_sub varchar(255) not null unique,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists business_users 
       add constraint FK90s3v7j9mmkrumt9gepf8j364 
       foreign key (agency_id) 
       references real_estate_agencies 
       on delete cascade;

    alter table if exists business_users 
       add constraint FK8aqcsipej5gvg66tb47nd3rx1 
       foreign key (user_id) 
       references users 
       on delete cascade;

    alter table if exists insertion_tags 
       add constraint FK1fkgc2aua4wltci62lb66hq9m 
       foreign key (tags) 
       references insertions;

    alter table if exists insertions 
       add constraint FKetfigcurqspg485ffulgund34 
       foreign key (address_id) 
       references addresses;

    alter table if exists insertions 
       add constraint FKn40jjk88ieau7s9l47vfvrrnh 
       foreign key (agency_id) 
       references real_estate_agencies 
       on delete set null;

    alter table if exists insertions 
       add constraint FK4fsr610gmfx97ke7ht0ib96gw 
       foreign key (uploader_id) 
       references users 
       on delete set null;

    alter table if exists insertions_for_rent 
       add constraint FKl3xibjaiyh0bqw800a77knhup 
       foreign key (id) 
       references insertions
       on delete cascade;

    alter table if exists insertions_for_sale 
       add constraint FKlnx1rg305866klh60e1g26xw1 
       foreign key (id) 
       references insertions
       on delete cascade;

    alter table if exists real_estate_agents 
       add constraint FK8pd1ulhpq4q4vjfjalhevo1tu 
       foreign key (user_id) 
       references business_users 
       on delete cascade;

    alter table if exists real_estate_managers 
       add constraint FKj51vf5rl536rksdrx9ball8eh 
       foreign key (user_id) 
       references business_users 
       on delete cascade;

    alter table if exists user_roles
       add constraint FK36x4o60s7xjf05xnwqd6mqin5
       foreign key (role_id)
       references dietiestates_roles;

    alter table if exists user_roles
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f
       foreign key (user_id)
       references users;

    create index if not exists addresses_location on addresses using gist(location);
    create index if not exists insertions_uploader_id on insertions(uploader_id);
    create index if not exists insertions_agency_id on insertions(agency_id);
    create index if not exists insertions_address_id on insertions(address_id);
    create index if not exists insertions_tags on insertion_tags(tags);
    create index if not exists insertions_for_rent_rent on insertions_for_rent(rent);
    create index if not exists insertions_for_sale_price on insertions_for_sale(price);
    create index if not exists business_users_agency_id on business_users(agency_id);
