CREATE TABLE addresses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location        GEOMETRY(Point, 4326)                   NOT NULL,
    country_code    VARCHAR(255),
    housenumber     VARCHAR(255),
    street          VARCHAR(255),
    country         VARCHAR(255),
    state           VARCHAR(255),
    state_code      VARCHAR(255),
    district        VARCHAR(255),
    city            VARCHAR(255),
    suburb          VARCHAR(255),
    county          VARCHAR(255),
    county_code     VARCHAR(255),
    result_type     VARCHAR(255),
    postcode        VARCHAR(255),
    formatted       VARCHAR(255),
    address_line1   VARCHAR(255),
    address_line2   VARCHAR(255),
    plus_code       VARCHAR(255),
    plus_code_short VARCHAR(255),
    iso3166dash2    VARCHAR(255),
    place_id        VARCHAR(255),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE business_users
(
    user_id   BIGINT NOT NULL,
    agency_id BIGINT NOT NULL,
    CONSTRAINT pk_business_users PRIMARY KEY (user_id)
);

CREATE TABLE dietiestates_roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_dietiestates_roles PRIMARY KEY (id)
);

CREATE TABLE insertion_tags
(
    insertion_id BIGINT NOT NULL,
    tag_id       BIGINT NOT NULL,
    CONSTRAINT pk_insertion_tags PRIMARY KEY (insertion_id, tag_id)
);

CREATE TABLE insertions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id  BIGINT                                  NOT NULL,
    uploader_id BIGINT                                  NOT NULL,
    agency_id   BIGINT                                  NOT NULL,
    description TEXT,
    CONSTRAINT pk_insertions PRIMARY KEY (id)
);

CREATE TABLE insertions_for_rent
(
    id   BIGINT NOT NULL,
    rent DOUBLE PRECISION,
    CONSTRAINT pk_insertions_for_rent PRIMARY KEY (id)
);

CREATE TABLE insertions_for_sale
(
    id    BIGINT NOT NULL,
    price DOUBLE PRECISION,
    CONSTRAINT pk_insertions_for_sale PRIMARY KEY (id)
);

CREATE TABLE real_estate_agencies
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    iban VARCHAR(255)                            NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_real_estate_agencies PRIMARY KEY (id)
);

CREATE TABLE real_estate_agents
(
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_real_estate_agents PRIMARY KEY (user_id)
);

CREATE TABLE real_estate_managers
(
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_real_estate_managers PRIMARY KEY (user_id)
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    cognito_sub VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE dietiestates_roles
    ADD CONSTRAINT uc_dietiestates_roles_name UNIQUE (name);

ALTER TABLE real_estate_agencies
    ADD CONSTRAINT uc_real_estate_agencies_iban UNIQUE (iban);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_cognitosub UNIQUE (cognito_sub);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE business_users
    ADD CONSTRAINT FK_BUSINESS_USERS_ON_AGENCY FOREIGN KEY (agency_id) REFERENCES real_estate_agencies (id) ON DELETE CASCADE;

ALTER TABLE business_users
    ADD CONSTRAINT FK_BUSINESS_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE insertions_for_rent
    ADD CONSTRAINT FK_INSERTIONS_FOR_RENT_ON_ID FOREIGN KEY (id) REFERENCES insertions (id) ON DELETE CASCADE;

ALTER TABLE insertions_for_sale
    ADD CONSTRAINT FK_INSERTIONS_FOR_SALE_ON_ID FOREIGN KEY (id) REFERENCES insertions (id) ON DELETE CASCADE;

ALTER TABLE insertions
    ADD CONSTRAINT FK_INSERTIONS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE insertions
    ADD CONSTRAINT FK_INSERTIONS_ON_AGENCY FOREIGN KEY (agency_id) REFERENCES real_estate_agencies (id) ON DELETE SET NULL;

ALTER TABLE insertions
    ADD CONSTRAINT FK_INSERTIONS_ON_UPLOADER FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE real_estate_agents
    ADD CONSTRAINT FK_REAL_ESTATE_AGENTS_ON_USER FOREIGN KEY (user_id) REFERENCES business_users (user_id) ON DELETE CASCADE;

ALTER TABLE real_estate_managers
    ADD CONSTRAINT FK_REAL_ESTATE_MANAGERS_ON_USER FOREIGN KEY (user_id) REFERENCES business_users (user_id) ON DELETE CASCADE;

ALTER TABLE insertion_tags
    ADD CONSTRAINT fk_instag_on_base_insertion FOREIGN KEY (insertion_id) REFERENCES insertions (id);

ALTER TABLE insertion_tags
    ADD CONSTRAINT fk_instag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_base_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES dietiestates_roles (id);