CREATE TABLE saved_searches
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    geometry            GEOMETRY(Geometry, 4326)                NOT NULL,
    distance            DOUBLE PRECISION                        NOT NULL,
    min_size            DOUBLE PRECISION,
    min_number_of_rooms INTEGER,
    max_floor           INTEGER,
    has_elevator        BOOLEAN,
    CONSTRAINT pk_saved_searches PRIMARY KEY (id)
);

CREATE TABLE saved_searches_for_rent
(
    id       BIGINT NOT NULL,
    max_rent DOUBLE PRECISION,
    CONSTRAINT pk_saved_searches_for_rent PRIMARY KEY (id)
);

CREATE TABLE saved_searches_for_sale
(
    id        BIGINT NOT NULL,
    max_price DOUBLE PRECISION,
    CONSTRAINT pk_saved_searches_for_sale PRIMARY KEY (id)
);

CREATE TABLE search_tags
(
    search_id  BIGINT NOT NULL,
    search_tag VARCHAR(255)
);

ALTER TABLE saved_searches_for_rent
    ADD CONSTRAINT FK_SAVED_SEARCHES_FOR_RENT_ON_ID FOREIGN KEY (id) REFERENCES saved_searches (id);

ALTER TABLE saved_searches_for_sale
    ADD CONSTRAINT FK_SAVED_SEARCHES_FOR_SALE_ON_ID FOREIGN KEY (id) REFERENCES saved_searches (id);

ALTER TABLE saved_searches
    ADD CONSTRAINT FK_SAVED_SEARCHES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE search_tags
    ADD CONSTRAINT fk_search_tags_on_saved_search FOREIGN KEY (search_id) REFERENCES saved_searches (id);

CREATE INDEX idx_saved_searches_user_id ON saved_searches (user_id);