CREATE TABLE notification_preferences
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    center  GEOMETRY(Geometry, 4326)                NOT NULL,
    radius  DOUBLE PRECISION                        NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_notification_preferences PRIMARY KEY (id)
);

CREATE TABLE notification_preferences_for_rent
(
    id       BIGINT NOT NULL,
    max_rent DOUBLE PRECISION,
    CONSTRAINT pk_notification_preferences_for_rent PRIMARY KEY (id)
);

CREATE TABLE notification_preferences_for_sale
(
    id        BIGINT NOT NULL,
    max_price DOUBLE PRECISION,
    CONSTRAINT pk_notification_preferences_for_sale PRIMARY KEY (id)
);

ALTER TABLE notification_preferences_for_rent
    ADD CONSTRAINT FK_NOTIFICATION_PREFERENCES_FOR_RENT_ON_ID FOREIGN KEY (id) REFERENCES notification_preferences (id);

ALTER TABLE notification_preferences_for_sale
    ADD CONSTRAINT FK_NOTIFICATION_PREFERENCES_FOR_SALE_ON_ID FOREIGN KEY (id) REFERENCES notification_preferences (id);

ALTER TABLE notification_preferences
    ADD CONSTRAINT FK_NOTIFICATION_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);